# Generated by Django 2.2.2 on 2019-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('ch', 'chocolate'), ('mr', 'morango'), ('pr', 'prestígio'), ('bl', 'baunilha'), ('nh', 'ninho'), ('cr', 'churros')], max_length=2)),
                ('recheio', models.CharField(choices=[('br', 'brigadeiro'), ('dl', 'doce de leite'), ('fv', 'frutas vermelhas'), ('nt', 'nutella'), ('bj', 'beijinho'), ('nh', 'ninho')], max_length=2)),
                ('cobertura', models.CharField(choices=[('gr', 'granulado'), ('ct', 'chantylly'), ('mr', 'morango'), ('sc', 'sem cobertura')], default='sc', max_length=2)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('cartao', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('av', 'pagamento à vista'), ('p2', 'parcelado em 2 vezes'), ('p3', 'parcelado em 3 vezes')], default='av', max_length=2)),
            ],
        ),
    ]
